import { StrictMode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { io } from "socket.io-client";
import "./styles.css";

type Difficulty = "easy" | "medium" | "hard";
type Question = { id: string; number: number; category: string; difficulty: Difficulty; text: string; options: string[]; correctOption: number };
type Team = { id: string; name: string; logo: string; description: string; theme: string; score: number };
type Attempt = { teamId: string; category: string; difficulty: Difficulty; questionId: string; correct: boolean; points: number };
type CardDetail = { logo: string; name: string; description: string; id?: string };
type Game = { rules: { gameTitle: string; seasonTitle: string; backgroundTheme: string; categories: string[]; categoryDetails: CardDetail[]; difficulties: Difficulty[]; difficultyDetails: CardDetail[]; pointsByDifficulty: Record<Difficulty, number>; incorrectPenalty: number; timerSeconds: number }; teams: Team[]; questionSets: Record<string, Record<Difficulty, Question[]>>; phase: string; activeTeamId: string | null; selectedCategory: string | null; selectedDifficulty: Difficulty | null; currentQuestion: Question | null; selectedOption: number | null; answerRevealed: boolean; usedQuestionIds: string[]; attempts: Attempt[]; timerEndsAt: number | null };
const API = "http://localhost:3000/api/game"; const ASSETS = "http://localhost:3000/assets"; const gameshowStage = `${ASSETS}/gameshow-stage.png`; const letters = ["A", "B", "C", "D"];
const teamBackdrops: Record<string, string> = { raw: `${ASSETS}/team-raw.png`, kgb: `${ASSETS}/team-kgb.png`, cia: `${ASSETS}/team-cia.png`, mossad: `${ASSETS}/team-mossad.png` };
function backgroundStyle(team?: Team) { return team ? { backgroundImage: `linear-gradient(rgba(5, 11, 18, 0.28), rgba(5, 11, 18, 0.28)), url(${teamBackdrops[team.id]})`, backgroundPosition: "center", backgroundSize: "cover" } : undefined; }
function hostBackgroundStyle(team?: Team) { return team ? backgroundStyle(team) : { backgroundImage: `linear-gradient(rgba(3, 8, 18, 0.45), rgba(3, 8, 18, 0.62)), url(${gameshowStage})`, backgroundPosition: "center", backgroundSize: "cover" }; }
function displayBackgroundStyle(team?: Team) { return team ? backgroundStyle(team) : { backgroundImage: `linear-gradient(rgba(3, 8, 18, 0.28), rgba(3, 8, 18, 0.5)), url(${gameshowStage})`, backgroundPosition: "center", backgroundSize: "cover" }; }
let audioContext: AudioContext | null = null;
let suspenseInterval: number | null = null;
let soundsMuted = false;
function context() { audioContext ??= new AudioContext(); return audioContext; }
function playTone(frequency: number, duration: number, type: OscillatorType, volume = 0.05, delay = 0) {
  if (soundsMuted) return;
  const audio = context();
  audio.resume().then(() => {
    const oscillator = audio.createOscillator(); const gain = audio.createGain(); const start = audio.currentTime + delay;
    oscillator.type = type; oscillator.frequency.setValueAtTime(frequency, start); gain.gain.setValueAtTime(0.0001, start);
    gain.gain.exponentialRampToValueAtTime(volume, start + 0.02); gain.gain.exponentialRampToValueAtTime(0.0001, start + duration);
    oscillator.connect(gain).connect(audio.destination); oscillator.start(start); oscillator.stop(start + duration + 0.03);
  });
}
const sounds = {
  setMuted(value: boolean) { soundsMuted = value; if (value) this.stopSuspense(); },
  playSelection() { playTone(540, 0.11, "triangle", 0.07); playTone(760, 0.14, "triangle", 0.05, 0.1); },
  playCorrect() { playTone(523, 0.12, "sine", 0.07); playTone(659, 0.14, "sine", 0.07, 0.12); playTone(784, 0.24, "sine", 0.08, 0.25); },
  playWrong() { playTone(220, 0.18, "sawtooth", 0.06); playTone(165, 0.32, "sawtooth", 0.06, 0.18); },
  startSuspense() { this.stopSuspense(); if (soundsMuted) return; const pulse = () => { playTone(110, 0.3, "sine", 0.025); playTone(165, 0.14, "triangle", 0.018, 0.38); }; pulse(); suspenseInterval = window.setInterval(pulse, 1100); },
  stopSuspense() { if (suspenseInterval !== null) { clearInterval(suspenseInterval); suspenseInterval = null; } }
};
async function action(path: string, body?: object) { await fetch(`${API}/${path}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: body ? JSON.stringify(body) : undefined }); }
function useGame() { const [game, setGame] = useState<Game | null>(null); useEffect(() => { fetch(API).then((r) => r.json()).then(setGame); const socket = io("http://localhost:3000"); socket.on("game-state", setGame); return () => { socket.disconnect(); }; }, []); return game; }
function activeTeam(game: Game) { return game.teams.find((team) => team.id === game.activeTeamId); }
function attempted(game: Game, category: string, difficulty: Difficulty) { return game.attempts.some((item) => item.teamId === game.activeTeamId && item.category === category && item.difficulty === difficulty); }
function categoryComplete(game: Game, category: string) { return game.rules.difficulties.every((difficulty) => attempted(game, category, difficulty)); }
function Timer({ until }: { until: number | null }) { const [remaining, setRemaining] = useState(0); useEffect(() => { const update = () => setRemaining(until ? Math.max(0, Math.ceil((until - Date.now()) / 1000)) : 0); update(); const id = window.setInterval(update, 250); return () => clearInterval(id); }, [until]); return <div className="rounded-full border-2 border-gold bg-panel px-7 py-3 text-2xl font-black text-gold">{remaining}s</div>; }

function Display({ game }: { game: Game }) {
  const team = activeTeam(game); const question = game.currentQuestion;
  if (game.phase === "landing") return <main className="landing grid min-h-screen place-items-center p-12 text-center" style={{ backgroundImage: `linear-gradient(rgba(3, 8, 18, 0.28), rgba(3, 8, 18, 0.5)), url(${gameshowStage})`, backgroundPosition: "center", backgroundSize: "cover" }}><div><p className="mb-5 text-gold font-bold uppercase tracking-[.4em]">Welcome to</p><h1 className="text-7xl font-black">{game.rules.gameTitle}</h1><p className="mt-5 text-3xl font-bold text-gold">{game.rules.seasonTitle}</p><p className="mt-6 text-xl text-slate-300">An intelligence challenge inspired by the world of Dhurandhar</p></div></main>;
  if (game.phase === "question-transition" && question) return <main className="min-h-screen p-12" style={backgroundStyle(team)}><Scoreboard game={game} /><div className="grid min-h-[80vh] place-items-center text-center"><div><p className="text-2xl font-bold uppercase tracking-[.25em] text-gold">{team?.name} has selected</p><div className="selected-tile mx-auto my-8 grid h-52 w-52 place-items-center rounded-3xl border-4 border-gold bg-ink/80 text-8xl font-black text-gold shadow-2xl">{question.number}</div><p className="text-3xl font-black">Get ready for the question…</p></div></div></main>;
  if (["team-selection", "category-selection", "difficulty-selection", "question-selection"].includes(game.phase)) {
    const heading = game.phase === "team-selection" ? "Select the next team" : game.phase === "category-selection" ? "Choose a category" : game.phase === "difficulty-selection" ? `${game.selectedCategory}: choose a difficulty` : "Choose a hidden question number";
    const cards: CardDetail[] = game.phase === "team-selection" ? game.teams : game.phase === "category-selection" ? game.rules.categoryDetails : game.phase === "difficulty-selection" ? game.rules.difficultyDetails : [];
    return <main className="landing min-h-screen p-12" style={displayBackgroundStyle(team)}><header><h1 className="text-4xl font-black">{game.rules.gameTitle}</h1><p className="text-lg font-bold text-gold">{game.rules.seasonTitle}</p></header><Scoreboard game={game} /><section className="mx-auto max-w-6xl text-center">{team && <div className="mb-5"><p className="text-lg text-gold">Now playing</p><p className="text-3xl font-black text-gold">{team.logo} {team.name}</p></div>}<h2 className="mb-10 text-5xl font-black">{heading}</h2>{game.phase === "question-selection" ? <div className="mx-auto grid max-w-3xl grid-cols-5 gap-4">{game.questionSets[game.selectedCategory!][game.selectedDifficulty!].map((question) => <div key={question.id} className={`rounded-2xl border-2 p-6 text-3xl font-black ${game.usedQuestionIds.includes(question.id) ? "border-slate-700 bg-slate-900 text-slate-600" : "border-gold bg-panel text-gold"}`}>{question.number}</div>)}</div> : <div className="grid gap-5 md:grid-cols-3">{cards.map((card) => { const locked = game.phase === "category-selection" && categoryComplete(game, card.name); const image = game.phase === "team-selection" && card.id ? teamBackdrops[card.id] : undefined; return <div key={card.name} style={image ? { backgroundImage: `linear-gradient(rgba(5, 11, 18, 0.25), rgba(5, 11, 18, 0.48)), url(${image})`, backgroundPosition: "center", backgroundSize: "cover" } : undefined} className={`rounded-2xl border p-7 ${locked ? "border-slate-800 bg-slate-950 text-slate-600" : "border-slate-600 bg-panel"}`}><div className="mb-3 text-5xl">{card.logo}</div><h3 className="text-2xl font-black">{card.name}</h3><p className="mt-2 text-slate-300">{locked ? "Completed by this team" : card.description}</p>{game.phase === "difficulty-selection" && card.id && <p className="mt-4 text-gold font-bold">{game.rules.pointsByDifficulty[card.id as Difficulty]} points</p>}</div>; })}</div>}</section></main>;
  }
  if (!question) return null;
  const result = game.phase === "answer-result"; const selected = game.selectedOption;
  return <main className="min-h-screen p-10" style={backgroundStyle(team)}><Scoreboard game={game} /><header className="mb-10 flex items-start gap-8"><div><p className="text-lg text-gold">Now playing</p><p className="text-3xl font-black text-gold">{team?.logo} {team?.name}</p><h1 className="mt-3 text-4xl font-black">{game.rules.gameTitle}</h1><p className="mt-1 text-lg font-bold text-gold">{game.rules.seasonTitle}</p><p className="mt-2 text-sm font-bold uppercase tracking-[.25em] text-slate-300">{question.category} · {question.difficulty}</p></div><Timer until={game.timerEndsAt} /></header><section className="question-reveal mx-auto max-w-6xl"><h2 className="mb-10 text-center text-5xl font-black leading-tight">{question.text}</h2><div className="grid grid-cols-2 gap-5">{question.options.map((option, index) => { const correct = result && question.correctOption === index; const wrong = result && selected === index && !correct; return <div key={option} className={`option-reveal rounded-2xl border-2 p-6 text-2xl font-bold ${correct ? "border-emerald-400 bg-emerald-500/20" : wrong ? "border-rose-400 bg-rose-500/20" : selected === index ? "border-gold bg-amber-500/20" : "border-slate-700 bg-panel"}`} style={{ animationDelay: `${index * 120}ms` }}><span className="mr-4 text-gold">{letters[index]}</span>{option}</div>; })}</div>{result && <p className="mt-8 text-center text-3xl font-black text-gold">{game.attempts.at(-1)?.correct ? `Correct! +${game.attempts.at(-1)?.points} points` : `Incorrect. -${game.rules.incorrectPenalty} points`}</p>}</section></main>;
}
function Scoreboard({ game }: { game: Game }) { return <div className="fixed right-6 top-6 z-10 flex max-w-[34rem] flex-wrap justify-end gap-2">{game.teams.map((team) => <div key={team.id} className={`rounded-xl border px-3 py-2 text-center shadow-xl ${team.id === game.activeTeamId ? "border-gold bg-ink/95 ring-2 ring-gold/50" : "border-slate-600 bg-ink/80"}`}><div className="text-xs text-slate-300">{team.logo} {team.name}</div><div className={`text-xl font-black ${team.id === game.activeTeamId ? "text-gold" : "text-slate-200"}`}>{team.score}</div></div>)}</div>; }

function Host({ game }: { game: Game }) {
  const team = activeTeam(game); const q = game.currentQuestion; const choices = game.selectedCategory && game.selectedDifficulty ? game.questionSets[game.selectedCategory][game.selectedDifficulty] : [];
  const [muted, setMuted] = useState(false);
  const canGoBack = ["team-selection", "category-selection", "difficulty-selection", "question-selection"].includes(game.phase);
  const resetGame = () => { if (window.confirm("Reset the entire game? This clears all team scores, attempted questions, and progress.")) { sounds.stopSuspense(); action("reset"); } };
  const toggleSound = () => { const next = !muted; setMuted(next); sounds.setMuted(next); };
  const title = <header className="mb-8 flex items-center justify-between"><div><p className="text-gold text-sm font-bold uppercase tracking-[.2em]">Host console</p><h1 className="text-3xl font-black">{game.rules.gameTitle}</h1><p className="text-lg font-bold text-gold">{game.rules.seasonTitle}</p></div><div className="flex gap-3">{canGoBack && <button onClick={() => action("back")} className="bg-slate-700">← Back</button>}<button onClick={toggleSound} className="bg-slate-700">{muted ? "🔇 Sound off" : "🔊 Sound on"}</button><button onClick={resetGame} className="bg-rose-700">Reset game</button><a className="rounded-lg bg-slate-700 px-4 py-3 font-bold" href="/?screen=display" target="_blank">Open projector display</a></div></header>;
  if (game.phase === "landing") return <main className="host" style={hostBackgroundStyle()}>{title}<Panel title="Start the game"><p className="mb-6 text-slate-300">The audience display is on the landing screen. Start when the show is ready to reveal the teams.</p><button onClick={() => action("start")} className="bg-gold text-ink">Reveal teams</button></Panel></main>;
  if (game.phase === "team-selection") return <main className="host" style={hostBackgroundStyle()}>{title}<Panel title="Select the next playing team"><div className="grid gap-3 md:grid-cols-2">{game.teams.map((item) => { const done = game.attempts.filter((a) => a.teamId === item.id).length === 12; return <button key={item.id} disabled={done} onClick={() => action("select-team", { teamId: item.id })} style={{ backgroundImage: `linear-gradient(rgba(5, 11, 18, 0.2), rgba(5, 11, 18, 0.55)), url(${teamBackdrops[item.id]})`, backgroundPosition: "center", backgroundSize: "cover" }} className="min-h-32 text-left"><span className="mr-3 text-3xl">{item.logo}</span><span>{item.name}<small className="block pl-10 text-slate-200">{item.description}</small></span><span className="float-right text-gold">{done ? "Complete" : `${item.score} pts`}</span></button>; })}</div></Panel></main>;
  if (game.phase === "category-selection") return <main className="host" style={hostBackgroundStyle(team)}>{title}<Panel title={`${team?.name}: select a category`}><div className="grid gap-4 md:grid-cols-2">{game.rules.categoryDetails.map((category) => { const locked = categoryComplete(game, category.name); return <button key={category.name} disabled={locked} onClick={() => action("select-category", { category: category.name })} className="bg-slate-700 text-left"><span className="mr-3 text-3xl">{category.logo}</span><strong className="text-2xl">{category.name}</strong><small className="ml-3 text-slate-300">{locked ? "Completed by this team" : category.description}</small></button>; })}</div></Panel></main>;
  if (game.phase === "difficulty-selection") return <main className="host" style={hostBackgroundStyle(team)}>{title}<Panel title={`${team?.name}: ${game.selectedCategory}`}><p className="mb-5 text-slate-300">Select a sub-category. Completed levels are unavailable for this team.</p><div className="grid gap-4 md:grid-cols-3">{game.rules.difficultyDetails.map((difficulty) => <button key={difficulty.id} disabled={attempted(game, game.selectedCategory!, difficulty.id as Difficulty)} onClick={() => action("select-difficulty", { difficulty: difficulty.id })} className="bg-slate-700 text-left"><span className="mr-3 text-2xl">{difficulty.logo}</span><strong className="text-xl">{difficulty.name}</strong><small className="block mt-2 text-slate-300">{difficulty.description}</small><span className="text-gold">{game.rules.pointsByDifficulty[difficulty.id as Difficulty]} pts</span></button>)}</div></Panel></main>;
  if (game.phase === "question-selection") return <main className="host" style={hostBackgroundStyle(team)}>{title}<Panel title={`${team?.name}: ${game.selectedCategory} / ${game.selectedDifficulty}`}><p className="mb-5 text-slate-300">Let the team select a numbered tile. The question remains hidden until selected.</p><div className="grid grid-cols-5 gap-3">{choices.map((question) => <button key={question.id} disabled={game.usedQuestionIds.includes(question.id)} onClick={() => { sounds.startSuspense(); action("select-question", { number: question.number }); }} className="bg-slate-700 text-2xl">{question.number}</button>)}</div></Panel></main>;
  if (!q) return null;
  if (game.phase === "question-transition") return <main className="host" style={hostBackgroundStyle(team)}>{title}<Panel title="Question selected"><p className="text-xl text-gold">Question {q.number} is being revealed on the projector…</p></Panel></main>;
  const answerSelected = game.selectedOption !== null;
  return <main className="host" style={hostBackgroundStyle(team)}>{title}<Panel title={`${team?.name}: question ${q.number}`}><p className="mb-5 text-sm uppercase tracking-wider text-gold">{q.category} · {q.difficulty} · {game.rules.pointsByDifficulty[q.difficulty]} points</p><h2 className="mb-6 text-3xl font-black">{q.text}</h2><div className="grid gap-3">{q.options.map((option, index) => <button key={option} disabled={answerSelected} onClick={() => { sounds.stopSuspense(); sounds.playSelection(); action("select-option", { optionIndex: index }); }} className={`text-left ${game.selectedOption === index ? "bg-gold text-ink" : "bg-slate-700"}`}><span className="mr-3 text-gold">{letters[index]}</span>{option}</button>)}</div>{game.phase === "answer-review" && <div className="mt-6"><button onClick={() => { sounds.stopSuspense(); game.selectedOption === q.correctOption ? sounds.playCorrect() : sounds.playWrong(); action("mark-answer"); }} className="bg-gold text-ink">Confirm answer and calculate score</button></div>}{game.phase === "answer-result" && <button onClick={() => action("continue")} className="mt-6 bg-gold text-ink">Continue</button>}</Panel></main>;
}
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl bg-panel p-7"><h2 className="mb-6 text-2xl font-black">{title}</h2>{children}</section>; }
function App() { const game = useGame(); if (!game) return <main className="grid min-h-screen place-items-center">Connecting to the quiz server…</main>; return new URLSearchParams(location.search).get("screen") === "display" ? <Display game={game} /> : <Host game={game} />; }
createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
